# basic tenets
title: aani
author: aani
email: i.alexanderani@gmail.com
description: Alexander Ani
instagram_username: alec_xander
linkedin_username: alexanderani

# Build settings
markdown: kramdown
theme: minima 
