# basic tenets
title: Configuration
author: aani
email: i.alexanderani@gmail.com
description: Temporary online presence
twitter_username: potus
linkedin_username: alexanderani

# Build settings
markdown: kramdown
theme: minima 
